controller_list:
  - name: fake_dofbot_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint5
initial:  # Define initial robot poses.
  - group: dofbot
    pose: up