
__all__ = ['ikpy_utils', 'torch_utils']
URDF_PATH = "/home/jetson/code/dofbot_ros2_ws/src/ros2_vision_arm_control/urdf/dofbot.urdf"
WEIGHT_PATH = "/home/jetson/code/dofbot_ros2_ws/src/ros2_vision_arm_control/yolo_weight/yolov5n_0214.pt"
TOPIC_CAMERA_RGB = "/camera/rgb_image"
TOPIC_CAMERA_DEPTH = "/camera/depth_image"
TOPIC_YOLO_DETECTION = "/yolo_detection"
TOPIC_YOLO_DEPTH = "/yolo_depth"
TOPIC_ROBOT_STATUS = "/robot_status"
TOPIC_ROBOT_TRANSFORM = "/robot_transform"
TOPIC_ARM_CONTROL = "/arm_control"
TOPIC_CAMERA_INFO = "/camera_info"
TEST_IMG_PATH = "/home/jetson/code/dofbot_ros2_ws/src/ros2_vision_arm_control/output0113_mov-0057.jpg"
VISUALIZATION = False
FRAME_RATE = 4
JOINT_INTERVAL = 0.5
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CLASS_NAMES = ['leaf','stem','tomato']