weights: yolov5s.pt
cfg: ./models/yolov5s.yaml
data: /home/jetson/code/yolov5/tomato/data.yaml
hyp: data/hyp.finetune.yaml
epochs: 3
batch_size: 16
img_size:
- 320
- 320
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
